project_name: VAIPE
exp_name: fgvc-custom
use_wandb: True
wandb_entity: hungcao0402
train_root: ~
val_root: ~
data_size: 384
num_workers: 2
batch_size: 16
model_name: swin-t
pretrained: ../weights/107_class.pt
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0005
max_epochs: 50
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 107
num_selects: 
  layer1: 2048
  layer2: 512
  layer3: 128
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 2
log_freq: 100
eval_freq: 10